name: 'Build and Test'

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12'

      - run: npm ci
      - run: npm run all

  test:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name != 'push' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set commit status as pending
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: 'Self Check'

      - name: Set final commit status
        uses: ./
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: 'Self Check'
